### ISSUE TITLE
Bitcoin

### ISSUE THREAD

**Issue by JoCrotaux** [JoCrotaux/time_series_forecasting#12]
J'ai fait un code "heuristique" sur le bitcoin (dossier BTC). Principe assez simple : si baisse significative de genre 10% par rapport au cours d'ouverture, achat dans l'espérance qu'il remonte dans la journée. C'est potentiellement gagnant au vu de l'histogramme. Il faut la dernière version de Barna. Il faudrait faire un chemin relatif pour le fichier mais ça marche pas avec ./

**Comment by Maxtille** [comment]
Essaye .. À la place de ./

**Comment by Maxtille** [comment]
Plus compliqué que ça mais résolu dans ce [commit : ](txt)[https://github.com/JoCrotaux/time_series_forecasting/commit/e61d46a288774e91c79786f0a0748b7930f4b545](url)
