### ISSUE TITLE
créer un wiki

### ISSUE THREAD

**Issue by JoCrotaux** [JoCrotaux/time_series_forecasting#9]

**Comment by Maxtille** [comment]
Alz je veux bien commencer ;)

**Comment by Maxtille** [comment]
Enfait, je ne peux pas commencer '_ _
Tu dois toi même créer un wiki et ensuite peut-être que si tu me donnes les droits pour le modifier je pourrai alors en faire quelque chose d'utile ;)

En bref : 

- [x] créer le wiki
- [x] s'assurer que je vais pouvoir le modifier

**Comment by JoCrotaux** [comment]
https://github.com/JoCrotaux/time_series_forecasting/invitations
